const PDFDocument = require('pdfkit');
const fs = require('fs');

// Enhanced PDF generation with better styling
async function generateStyledPDF(reportContent, fileName, filePath) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ 
      margin: 40,
      size: 'A4',
      info: {
        Title: 'AI Career Counseling Report',
        Author: 'AI Counseling Platform',
        Subject: 'Personalized Career Guidance',
        Creator: 'AI Counseling System'
      }
    });

    const writeStream = fs.createWriteStream(filePath);
    doc.pipe(writeStream);

    // Header
    doc.fontSize(20)
       .fillColor('#2563eb')
       .text('🎓 AI Career Counseling Report', { align: 'center' });
    
    doc.fontSize(12)
       .fillColor('#64748b')
       .text(`Generated on ${new Date().toLocaleDateString('en-IN')} at ${new Date().toLocaleTimeString('en-IN')}`, { align: 'center' });
    
    doc.moveDown(2);

    // Process content with enhanced formatting
    const lines = reportContent.split('\n');
    let currentFontSize = 10;
    let inCodeBlock = false;

    lines.forEach(line => {
      line = line.trim();
      
      if (!line) {
        doc.moveDown(0.3);
        return;
      }

      // Handle different markdown elements
      if (line.startsWith('###')) {
        doc.fontSize(12).fillColor('#1e40af').font('Helvetica-Bold');
        doc.text(line.substring(3).trim());
        doc.moveDown(0.3);
      } else if (line.startsWith('##')) {
        doc.fontSize(14).fillColor('#1e3a8a').font('Helvetica-Bold');
        doc.text(line.substring(2).trim());
        doc.moveDown(0.5);
      } else if (line.startsWith('#')) {
        doc.fontSize(16).fillColor('#1e293b').font('Helvetica-Bold');
        doc.text(line.substring(1).trim());
        doc.moveDown(0.7);
      } else if (line.startsWith('- ') || line.startsWith('* ')) {
        doc.fontSize(10).fillColor('#374151').font('Helvetica');
        doc.text('• ' + parseEnhancedMarkdown(line.substring(2)), { 
          indent: 15,
          paragraphGap: 2
        });
      } else if (line.match(/^\d+\.\s/)) {
        doc.fontSize(10).fillColor('#374151').font('Helvetica');
        doc.text(parseEnhancedMarkdown(line), { 
          indent: 15,
          paragraphGap: 2
        });
      } else if (line.startsWith('```')) {
        inCodeBlock = !inCodeBlock;
        return;
      } else if (inCodeBlock) {
        doc.fontSize(9).fillColor('#1f2937').font('Courier');
        doc.text(line, { indent: 20 });
      } else {
        // Regular paragraph
        doc.fontSize(10).fillColor('#374151').font('Helvetica');
        doc.text(parseEnhancedMarkdown(line), { 
          align: 'justify',
          paragraphGap: 3
        });
      }
      
      doc.moveDown(0.2);
    });

    // Footer
    doc.fontSize(8)
       .fillColor('#9ca3af')
       .text('This report is generated by AI and should be used as guidance. Consult with career counselors for personalized advice.', 
             { align: 'center', valign: 'bottom' });

    doc.end();

    writeStream.on('finish', () => {
      const stats = fs.statSync(filePath);
      resolve(stats.size);
    });

    writeStream.on('error', reject);
  });
}

// Enhanced markdown parser
function parseEnhancedMarkdown(text) {
  // Bold text
  text = text.replace(/\*\*(.*?)\*\*/g, '$1');
  // Italic text  
  text = text.replace(/\*(.*?)\*/g, '$1');
  // Inline code
  text = text.replace(/`([^`]+)`/g, '$1');
  // Remove extra formatting
  text = text.replace(/^\s*[-*+]\s*/, '');
  
  return text;
}

module.exports = {
  generateStyledPDF,
  parseEnhancedMarkdown
};
